Bugs
NewShiftStudio/gour-store-front pull request #102
Opened 2022-09-19 07:54 UTC by avorokhta

2022-09-20 22:47 UTC, mirageN1349 requested changes

2022-09-20 22:47 UTC, mirageN1349 commented on components/Auth/Signup/Credentials/Credentials.tsx
> +                // disabled={codeCheckIsLoading}
А в чем тут проблема?

2022-09-20 22:47 UTC, mirageN1349 commented on pages/auth/signup.tsx
> +  // const [isPhoneCodeValid, setIsPhoneCodeValid] = useState(false);
Это точно должно быть так ?

2022-09-21 14:03 UTC, avorokhta commented on components/Auth/Signup/Credentials/Credentials.tsx
> +                // disabled={codeCheckIsLoading}
мы вроде обсуждали, он добавляет свойство cursor, с которым ошибки происходят

2022-09-21 14:04 UTC, avorokhta commented on pages/auth/signup.tsx
> +  // const [isPhoneCodeValid, setIsPhoneCodeValid] = useState(false);
> Это точно должно быть так ?

может после мержа)

2022-09-22 10:41 UTC, merged