Feat: почтовые коды подтверждения
NewShiftStudio/gour-store-front pull request #132
Opened 2022-10-01 15:33 UTC by avorokhta

2022-10-01 15:33 UTC, zolkinka commented
Task linked: [TSX-3767 Добавить отправку кода на email при его смене](https://app.clickup.com/t/4712744/TSX-3767)

2022-10-03 13:41 UTC, H0JLuk requested changes

2022-10-03 13:41 UTC, H0JLuk commented on components/Auth/Signup/Credentials/Credentials.tsx
> +    if (value.length === 4) checkCode();
передай сразу value в функцию

2022-10-03 13:41 UTC, H0JLuk commented on components/Auth/Signup/Credentials/Credentials.tsx
> +                onChange={event => changeCode(event.target.value)}
используй лучше _e_ для ивента, чтобы не загрязнять jsx

2022-10-03 13:41 UTC, H0JLuk commented on components/PA/Credentials/EmailChangeModal/EmailChangeModal.tsx
> +      setSeconds(sec => sec - 1);
выше описал по интервалу

2022-10-03 13:41 UTC, H0JLuk commented on pages/personal-area/credentials/index.tsx
> +    password: '1234567890',
?

2022-10-03 13:41 UTC, H0JLuk commented on components/PA/Credentials/Editor/Editor.tsx
> +    onSubmit({ firstName, lastName, phone, referralCode });
а где email?

2022-10-04 09:28 UTC, avorokhta commented on components/Auth/Signin/PassRecovery/PassRecovery.tsx
> +    else values.setError('email', { message: '' });
> пустая ошибка

там уведомление выводится, решил что тут достаточно валидность поля поменять

2022-10-04 09:30 UTC, avorokhta commented on pages/personal-area/credentials/index.tsx
> +    password: '1234567890',
так было до этого, чтобы поле пустым не казалось... типа пароль есть...

2022-10-04 09:31 UTC, avorokhta commented on components/PA/Credentials/Editor/Editor.tsx
> +    onSubmit({ firstName, lastName, phone, referralCode });
> а где email?

он же отдельно редактируется

2022-10-04 14:13 UTC, H0JLuk approved these changes
крута!

2022-10-04 14:52 UTC, merged