fix: 🐛 chapter links
NewShiftStudio/gour-store-front pull request #161
Opened 2022-10-17 12:06 UTC by avorokhta

2022-10-17 12:06 UTC, zolkinka commented
Task linked: [CU-47ze39g Пользователь не может открыть ссылки в новой вкладке нажатием на элемент/ссылку](https://app.clickup.com/t/47ze39g)

2022-10-18 14:42 UTC, H0JLuk requested changes

2022-10-18 14:42 UTC, H0JLuk commented on components/UI/List/List.tsx
> +} & Pick<ListItemButtonProps, 'children' | 'sx'>;
Utility types, еееее)

2022-10-18 15:09 UTC, avorokhta commented on components/UI/List/List.tsx
> +} & Pick<ListItemButtonProps, 'children' | 'sx'>;
могу без этого)

2022-10-19 09:10 UTC, H0JLuk approved these changes

2022-10-19 09:12 UTC, merged