feat: 🎸 жизни в игре, уведомления о статусе игры
NewShiftStudio/gour-store-front pull request #164
Opened 2022-10-18 07:37 UTC by H0JLuk

2022-10-18 07:37 UTC, zolkinka commented
Task linked: [TSX-3957 Добавить вывод кол-ва жизней под кнопкой "старт" и уведомление, если их нет](https://app.clickup.com/t/4712744/TSX-3957)

2022-10-19 06:42 UTC, mirageN1349 requested changes

2022-10-19 06:42 UTC, mirageN1349 commented on components/Game/Main/Main.tsx
> +      dispatchNotification('Пополните жизни в магазине', { type: NotificationType.DANGER });
Давай может статус INFO? Это все таки не ошибка

2022-10-19 06:42 UTC, mirageN1349 commented on components/Game/Main/Main.tsx
> +      dispatchNotification('Пополните жизни в магазине', { type: NotificationType.DANGER });
Ну для пользователя, а просто уведомление

2022-10-19 06:42 UTC, mirageN1349 commented on pages/game/index.tsx
> +    refetchCurrentUser();
А может это как-то через теги тулкита сделать?

2022-10-19 08:30 UTC, H0JLuk commented on pages/game/index.tsx
> +    refetchCurrentUser();
можно, я псевдокод написал скорее)

2022-10-19 09:20 UTC, H0JLuk commented on pages/game/index.tsx
> +    refetchCurrentUser();
давай пока что моканый запрос сделать, который будет отнимать жизнь

2022-10-26 12:35 UTC, mirageN1349 approved these changes

2022-10-26 12:36 UTC, mirageN1349 approved these changes

2022-10-26 13:13 UTC, merged