fix: выбор профиля доставки
NewShiftStudio/gour-store-front pull request #171
Opened 2022-10-19 16:03 UTC by avorokhta

2022-10-19 16:03 UTC, zolkinka commented
Task linked: [CU-30ja7hg Адрес из выпадающего списка сохранённых адресов не добавляется по клику](https://app.clickup.com/t/30ja7hg)

2022-10-21 10:30 UTC, H0JLuk requested changes

2022-10-21 10:30 UTC, H0JLuk commented on pages/order/index.tsx
> +  deliveryProfileId: -1,
а можно без -1?

2022-10-21 10:30 UTC, H0JLuk commented on pages/order/index.tsx
> +    if (deliveryProfileId !== -1) {
через null можешь переписать?
или хотя бы вынеси эту -1 в константу, которая объясняет, зачем -1 нужно

2022-10-21 10:30 UTC, H0JLuk commented on pages/order/index.tsx
> +    if (deliveryProfileId !== -1) {
типа, noExistingDelivery (назови более подходяще)

2022-10-21 10:30 UTC, H0JLuk commented on pages/order/index.tsx
> +    if (mainOrderProfileId && mainOrderProfileId !== -1)
и тут -1

2022-10-21 10:30 UTC, H0JLuk commented on pages/order/index.tsx
> +    if (mainOrderProfileId && mainOrderProfileId !== -1)
это вообще не очевидно, что за проверка на -1
мб специфичный безнес-кейс, мб что-то еще

2022-10-21 11:00 UTC, avorokhta commented on pages/order/index.tsx
> +  deliveryProfileId: -1,
![image](https://user-images.githubusercontent.com/93992220/197180913-a1a4c070-7f24-49f1-acce-8f012a304735.png)

2022-10-24 12:22 UTC, H0JLuk approved these changes

2022-10-24 12:24 UTC, merged