fix: валидация почты на кириллицу
NewShiftStudio/gour-store-front pull request #173
Opened 2022-10-20 12:07 UTC by avorokhta

2022-10-20 12:07 UTC, zolkinka commented
Task linked: [CU-47ze3f5 В поле "Электронная почта" можно вводить русский текст](https://app.clickup.com/t/47ze3f5)

2022-10-21 10:03 UTC, H0JLuk requested changes

2022-10-21 10:03 UTC, H0JLuk commented on components/PA/Credentials/EmailChangeModal/EmailChangeModal.tsx
> +  const { seconds, startCount, stopCount } = useStopwatch(30);
Ты избежал дублирования кода, вынеся таймер в хук, но не избежал дублирование вызова хука

2022-10-21 10:03 UTC, H0JLuk commented on constants/regex.ts
> +const cyrillic = /[а-яА-ЯёЁ]/g;
hasCyrillic, тк регулярка проверяет только наличие символов

2022-10-21 10:03 UTC, H0JLuk commented on constants/regex.ts
> +const cyrillic = /[а-яА-ЯёЁ]/g;
/[а-яё]/gi

флаг i не чувствителен к регистру

2022-10-21 10:57 UTC, avorokhta commented on components/PA/Credentials/EmailChangeModal/EmailChangeModal.tsx
> +  const { seconds, startCount, stopCount } = useStopwatch(30);
![image](https://user-images.githubusercontent.com/93992220/197180430-90b548c9-69dc-4f96-ae8c-f2d5d0729997.png)

2022-10-24 12:25 UTC, H0JLuk approved these changes

2022-10-24 12:25 UTC, merged