feat: 🎸 функциональность для пополнения чизкоинов в layouts
NewShiftStudio/gour-store-front pull request #178
Opened 2022-10-25 07:16 UTC by H0JLuk

2022-10-25 07:16 UTC, zolkinka commented
Task linked: [TSX-3974 Страница оплаты, открываемая после нажатия на пополнение в игре](https://app.clickup.com/t/4712744/TSX-3974)

2022-10-25 11:30 UTC, mirageN1349 requested changes

2022-10-25 11:30 UTC, mirageN1349 commented on layouts/Shop/Shop.tsx
> +          onClickAddCoins={() => toggleCheeseCoinModalOpen(true)}
Вынести в отдельную функцию

2022-10-25 11:30 UTC, mirageN1349 commented on layouts/PA/PA.tsx
> +          userEmail={currentUser?.email}
email может не быть?

2022-10-25 11:30 UTC, mirageN1349 commented on layouts/PA/PA.tsx
> +          onClickAddCoins={() => toggleCheeseCoinModalOpen(true)}
Вынести в отдельную функцию

2022-10-25 12:08 UTC, H0JLuk commented on layouts/PA/PA.tsx
> +          onClickAddCoins={() => toggleCheeseCoinModalOpen(true)}
готово

2022-10-25 12:12 UTC, H0JLuk commented on layouts/PA/PA.tsx
> +          userEmail={currentUser?.email}
currentUser достаю из хука c запросом, для типов через ?. достаю

могу через ! достать, разницы не будет, тк при загрузке страницы итак этот запрос заполняется, но безопаснее так)

2022-10-26 08:52 UTC, H0JLuk commented on layouts/Shop/Shop.tsx
> +          onClickAddCoins={() => toggleCheeseCoinModalOpen(true)}
готово

2022-10-26 12:35 UTC, mirageN1349 approved these changes

2022-10-26 12:54 UTC, merged