feat: 🎸 система скидок
NewShiftStudio/gour-store-front pull request #247
Opened 2022-12-06 10:33 UTC by avorokhta

2022-12-06 10:33 UTC, zolkinka commented
Task linked: [TSX-4613 Добавить промокоды](https://app.clickup.com/t/4712744/TSX-4613)

2022-12-06 23:23 UTC, H0JLuk requested changes

2022-12-06 23:23 UTC, H0JLuk commented on components/Order/Card/Card.tsx
> +    const priceByGram = getPriceByGrams(product.product.price.cheeseCoin, product.gram) * product.amount;
в `price.cheeseCoin` лежит значение со скидками?

2022-12-06 23:23 UTC, H0JLuk commented on components/Order/Form/Form.tsx
> +  referralCodeDiscount?: number;
миллион пропсов, в проекте оч часто такое юзается(
в будущем не делать так, плиз... Лучше использовать стор в компонентах/прокидывать объекты, чем _props drilling_ такой

2022-12-06 23:23 UTC, H0JLuk commented on components/Order/Form/FormDocket.tsx
> +import sx from './FormDocket.styles';
Cheers!

2022-12-06 23:23 UTC, H0JLuk commented on components/Order/Form/FormDocket.tsx
> +  const total = cost + delivery - promotionsDiscount - (promoCodeDiscount || referralCodeDiscount);
уф( не лучше этот расчет вынести в totalCost, как раньше было реализовано?

2022-12-06 23:23 UTC, H0JLuk commented on pages/order/index.tsx
> +  const [applyPromoCode, { isLoading: isPromoCodeApply }] = useApplyPromoCodeMutation();
переименуй isPromoCodeApply, непонятное название

2022-12-06 23:23 UTC, H0JLuk commented on pages/order/index.tsx
> +      if (isUseful) {
мб попробовать вынести логику из компонента в хелпер? компонент по 500 строк, сложно разобраться

2022-12-06 23:23 UTC, H0JLuk commented on store/api/commonApi.ts
> +    'PromoCode',
тег указал, но нигде не используешь его

2022-12-07 09:11 UTC, avorokhta commented on store/api/commonApi.ts
> +    'PromoCode',
какой ужас)

2022-12-07 09:12 UTC, avorokhta commented on pages/order/index.tsx
> +  const [applyPromoCode, { isLoading: isPromoCodeApply }] = useApplyPromoCodeMutation();
isPromoCodeApplies?)

2022-12-07 09:12 UTC, avorokhta commented on pages/order/index.tsx
> +  const [applyPromoCode, { isLoading: isPromoCodeApply }] = useApplyPromoCodeMutation();
или на check могу заменить

2022-12-07 12:14 UTC, avorokhta commented on components/Order/Card/Card.tsx
> +    const priceByGram = getPriceByGrams(product.product.price.cheeseCoin, product.gram) * product.amount;
там со со скидкой по ролям только

2022-12-07 12:29 UTC, avorokhta commented on components/Order/Form/FormDocket.tsx
> +  const total = cost + delivery - promotionsDiscount - (promoCodeDiscount || referralCodeDiscount);
не понял тебя
что не так то?

2022-12-08 12:42 UTC, avorokhta commented on components/Order/Form/FormDocket.tsx
> +  const total = cost + delivery - promotionsDiscount - (promoCodeDiscount || referralCodeDiscount);
там же всё равно есть вывод всего этого по отдельности, на карточке

2022-12-08 12:44 UTC, avorokhta commented on components/Order/Form/FormDocket.tsx
> +  const total = cost + delivery - promotionsDiscount - (promoCodeDiscount || referralCodeDiscount);
как промокод для ты предлагаешь высчитывать я тоже немного не понимаю, он же применяется к сумме всего заказа, а не отдельно к цене каждого продукта

2022-12-09 06:47 UTC, H0JLuk commented on components/Order/Form/FormDocket.tsx
> +  const total = cost + delivery - promotionsDiscount - (promoCodeDiscount || referralCodeDiscount);
аа, ну да, тогда ок
полный перерасчет цены нет смысла на бэк сейчас нет смысла переписывать

2022-12-09 06:48 UTC, H0JLuk approved these changes

2022-12-12 08:55 UTC, merged